from enum import Enum

class CommandEnum(Enum):
    BRING_ITEM = 'BRING_ITEM'
    BRING_TRAY = 'BRING_TRAY'
    BRING_CUT = 'BRING_CUT'
    BRING_EMPTY = 'BRING_EMPTY'
    PICK = 'PICK'
    PUT = 'PUT'
    PUT_CUT = 'PUT_CUT'
    STATION_MOVE = 'STATION_MOVE'
    LU_LOAD = 'LU_LOAD'
    LU_UNLOAD = 'LU_UNLOAD'
    LU_LOADUNLOAD = 'LU_LOADUNLOAD'
    LU_RESTTOTOWER = 'LU_RESTTOTOWER'
    LU_PICKUNLOADTRAY = "LU_PICKUNLOADTRAY"
    LU_PREPARE = 'LU_PREPARE'

class CommandStatus(Enum):
    NEW = 0
    READ = 1
    SEND_TO_PLC = 2
    SUCCESS = 100
    ERROR_PARAMETER = 1010
    ERROR_CANCEL = 1020
    ERROR_SQL_PROCEDURE = 2000
    REJECTED = 3000
